// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package orm

import (
	"github.com/google/uuid"
)

type Game struct {
	ID   uuid.UUID
	Name string
}

type Pick struct {
	ID       uuid.UUID
	GameID   uuid.UUID
	PickedBy uuid.UUID
	PlayerID uuid.UUID
}

type Player struct {
	ID        uuid.UUID
	Name      string
	GameID    uuid.UUID
	HasPicked bool
	IsPicked  bool
}
