// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main id=\"component\" class=\"container\"></main><script>\r\n        var component = document.getElementById(\"component\");\r\n        var form = document.getElementById(\"create_form\");\r\n\r\n        var players = [];\r\n\r\n        function addPlayer(e) {\r\n            e.preventDefault();\r\n\r\n            var name = document.getElementById(\"player\").value;\r\n            players.push(name);\r\n            document.getElementById(\"player\").value = \"\";\r\n        }\r\n\r\n        m.mount(component, {\r\n            view: () => [\r\n                m(\"h1\", \"Criar Amigo Oculto\"),\r\n                m(\"form\", {action: \"/\", method: \"POST\"}, [\r\n                    m(\"input\", {type: \"text\", name: \"name\", id: \"name\", placeholder: \"Escolha um nome para o amigo oculto\"}),\r\n                    m(\"input\", {type: \"hidden\", name: \"players\", value: players}),\r\n                    [\r\n                        m(\"ul\", players.map((player) => m(\"li\", player)))\r\n                    ],\r\n                    m(\"input\", {type: \"text\", name: \"player\", id: \"player\", placeholder: \"Nome do participante\"}),\r\n                    m(\"button\", {type: \"button\", onclick: addPlayer}, \"Adicionar\"),\r\n                    m(\"button\", {type: \"submit\"}, \"Criar\")\r\n                ])\r\n            ]\r\n        })\r\n    </script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
